# Generated by Django 4.2.1 on 2023-05-23 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='-03:00', max_length=50)),
                ('language', models.CharField(default='pt', max_length=2)),
                ('created_by', models.DateField(max_length=36)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('deadline', models.DateField()),
                ('signed', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('verified_email', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=100)),
                ('deadline', models.DateField()),
                ('signed', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
